### ISSUE TITLE
40mb Limit on HEN

### ISSUE THREAD

**Issue by MikeiLL** [OrderAndCh4oS/hicetnunc-radio#1]
Great work, folks. I hope I can find time to contribute.

Does anyone know why there is a 40mb limit on HEN and if that might be increased in the near future?

**Comment by OrderAndCh4oS** [comment]
Probably to save load on the FE, many profiles struggle even with 40mb limit. The files served on profiles aren't resized/scaled-down (though work is happening in this area), they're served at full size. Best to ask this in #help on discord if you want to know more.

**Comment by MikeiLL** [comment]
Okay thanks. Will request an invite to join discord and please pardon the spam.
